### ISSUE TITLE
Core dumped when training tree CRF (--type=tree) model

### ISSUE THREAD

**Issue by usptact** [WladimirSidorenko/CRFSuite#6]
I managed to successfully compile the tool but unfortunately I get the core dumped error when attempting to train tree CRF (-t tree). The training data file used was taken from "tests/test_tree_2.input"

The command run from console:
`crfsuite learn -t tree -m model test_tree_2.input`

The output:
```
[SKIPPING TRAINING ITERATION INFO]
L-BFGS resulted in convergence
Total seconds required for training: 0.000

*** Error in `/home/vladislavsd/bin/crfsuite': free(): invalid pointer: 0x0000000000b43d30 ***
Aborted (core dumped)
```

What can be the issue? I made sure that the crfsuite is linked to the appropriate libs and does not link against the chokkan's crfsuite libs.

**Comment by WladimirSidorenko** [comment]
I cannot reproduce this problem:
```shell
>git status
On branch master

>git log -1
commit 9018c979c74031341711106897309633fc9ef0a9

>make clean

>autoreconf

>make

>./frontend/crfsuite learn -t tree -m model tests/test_tree_2.input && echo $?
...
0

>uname -srm
Linux 3.19.0-42-generic x86_64

>./frontend/crfsuite --version
CRFSuite 0.13  Copyright (c) 2007-2011 Naoaki Okazaki
```

**Comment by usptact** [comment]
Thanks @WladimirSidorenko for running this check. It might be still that the standard CRFSuite libs are interfering with your version.

I didn't have any other Linux box in reach so I tried to install and run on Raspberry Pi. It worked!
