### ISSUE TITLE
Is tree structure known during prediction?

### ISSUE THREAD

**Issue by usptact** [WladimirSidorenko/CRFSuite#7]
During training time, one must provide training examples - trees. What about at the prediction stage? Should the tree be predefined? Will an algorithm only label the nodes of the tree?

I am having a problem to map a sequence to a tree. My training set is comprised of tuples - (sequence,tree). In the prediction stage, I am only given sequences. The algorithm should infer the structure of the tree and also label the nodes. Finally, the tree in the output can have more nodes than elements in the input sequence. Can you suggest something here?

Thanks

**Comment by WladimirSidorenko** [comment]
For the tree-CRFs, the tree structure of an input instance should be known in advance both during training and testing.  From your description, I assume that you need some kind of a parser rather than sequence labeler.

**Comment by usptact** [comment]
Thanks @WladimirSidorenko ! This is what I thought too! Closing this issue.
